services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - NGINX_AUTORELOAD= #optional
      - NGINX_AUTORELOAD_WATCHLIST= #optional
    volumes:
      - /media/fileserver/docker-configs/nginx:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    name: serverrumah
    external: true
