---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Jakarta
      #- JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /media/fileserver/docker-configs/jellyfin:/config
      - /media/fileserver/Data_for_NAS/Media/Animes:/data/animes
      - /media/fileserver/Data_for_NAS/Media/Movies:/data/movies
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    # devices:
      # devices di-bawah ini dikhususkan untuk perangkat Raspberry Pi
      # - /dev/video10:/dev/video10
      # - /dev/video11:/dev/video11
      # - /dev/video12:/dev/video12
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    name: serverrumah
    external: true
